POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "Akool07",
    "name": "John Cena",
    "password": "Codingrocks2023"
}
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "Dhoni07",
    "name": "MS Dhoni",
    "password": "Cricketrocks2023"
}